server:
  port: 8080

mini_program:
  app_id: 微信小程序AppID
  app_secret: 微信小程序AppSecret

mysql:
  driver: mysql # 数据库驱动
  host: 127.0.0.1 # 域名
  port: 3306 # 端口号
  database: workflow # 数据库名称
  username: root # 用户名
  password: Mysqlxwy9264 # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称

jwt:
  secret: 你的Jwt密钥
  jwt_ttl: 432000

elasticsearch:
  addresses:
    - http://你的ES IP:你的ES Port

redis:
  host: 你的Redis IP
  port: 你的Redis Port
  max_idle: 10
  max_active: 12000
  idle_timeout: 180
  password: ""
  dial_read_timeout: 1
  dial_write_timeout: 1

logger:
  debugFileName: "logs/debug.log"
  infoFileName: "logs/info.log"
  warnFileName: "logs/warn.log"
  errorFileName: "logs/error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3

qiniu:
  bucket: 你的七牛文件桶名
  access_key: 你的七牛AccessKey
  secret_key: 你的七牛SecretKey
  expire: 1800 
  host: 你的七牛绑定的域名